### PR TITLE
Anonymous profile photo

### PR DESCRIPTION
**Pull request by Vicopem01**
Link to closed pr [here](https://github.com/Aview-International/aviewint-website/pull/296)

### CODE REVIEW

**Comment by Vicopem01** [comment]
closes #299

**Comment by Vicopem01** [comment]
closes #298

**Comment by Vicopem01** [comment]
closes #295

**Comment by Vicopem01** [comment]
Screenshot 2024-07-18 at 12 52 26 PM

@d-huliu , let's also do the same for this page `/dashboard/settings/languages`

**Comment by Vicopem01** [comment]
this can be closed when it's done

**Comment by Vicopem01** [comment]
resolves #294

**Comment by d-huliu** [comment]
I just pushed this commit to the original anonymous-pfp branch--I don't know how to attach the original branch here

**Pull request merged**
