### PR TITLE
feat: creates the video status and recommended videos in the dashboard

### PR DESCRIPTION
**Pull request by chandhuDev**

### CODE REVIEW

**Comment by chandhuDev** [comment]
@Vicopem01 can you please review this one also!

**Comment by Vicopem01** [comment]
Screenshot 2024-03-04 at 3 58 17 PM

## On the dashboard, we already have the history page fetching the data, so just pick the latest two according to date and display on the dashboard

**Comment by Vicopem01** [comment]
The top two will always be the most recent ones, and also, there are some **flex** **flex-col** and **gap** properties that can all be replaced with just margin-top or margin-bottom or both, let's try to remove stylings that don't make impacts

**Comment by Vicopem01** [comment]
Like we discussed, we have

1. Queued
2. Transcription
3. Translation
4. Dubbing
5. Audio Separation
6. Editing
7. Complete


You can use this to calculate the percentage width of the progress bar.

**Comment by Vicopem01** [comment]
One more thing, only show the top two that are not less than 24 hours old. And display a settings icon that is rolling to show users that it's a work in progress

**Comment by Vicopem01** [comment]
@chandhuDev

**Comment by Vicopem01** [comment]
Pull changes before you proceed

**Pull request merged**
