### PR TITLE
Mobile plans

### PR DESCRIPTION
**Pull request by d-huliu**
I would still like to try to implement the slider recc feature later, but so far unsuccessful.

### CODE REVIEW

**Comment by Vicopem01** [comment]
@chandhuDev , #254 is the issue we're working on, please check the issue for more info about this task. we want to fix the mobile design of the pricing page, lemme know if you need anything

**Comment by Vicopem01** [comment]
also, @chandhuDev make sure to checkout into david's branch **mobile-plans** so you can have the most recent code for this task, and push your changes back into this branch

**Comment by Vicopem01** [comment]
@chandhuDev , the task has not been resolved and I've reassigned this back to David

**Comment by d-huliu** [comment]
my most recent commit "working highlight slider???" should be the final thing

**Pull request merged**
