### PR TITLE
Dashboard fixes

### PR DESCRIPTION
**Pull request by chandhuDev**
hey sorry @Vicopem01 i forgot to change the branch to beta while making PR

### CODE REVIEW

**Comment by Vicopem01** [comment]
@chandhuDev , this needs a little refix, will attach some screenshot

**Comment by Vicopem01** [comment]
Screenshot 2024-05-22 at 12 01 31 PM
this is what we want to recreate.

**Comment by chandhuDev** [comment]
hey quick question how we gonna get the values of each dubbing, translation, voice-overs service? Should we have to get those values from completed and pending videos? @Vicopem01

**Comment by Vicopem01** [comment]
closing this pr because it now continues from #277

**Pull request closed without merging**
